Requirement: Containerize application environment
GymmyComm/genki pull request #3
Opened 2023-04-30 02:56 UTC by InbaKrish

Feature:
Add Docker compose for the application
Use ruby3.2.2 base image for application Dockerfile Add dockerignore and gitignore for better management

2023-05-07 13:49 UTC, radar07 requested changes
@InbaKrish Thanks for working on this. Please have a look at my comments.

Also, don't pull bullet points in the header of the Git commit message.

2023-05-07 13:49 UTC, radar07 commented on README.md
> +1. Execute the `docker-compsoe up` command inside the project directory to run the rails server along with the database.
@InbaKrish Please fix the typo here. It should be **docker-compose up**.

2023-05-07 13:49 UTC, radar07 commented on Dockerfile
> +RUN apt-get update && apt-get install -y curl yarn nodejs postgresql-client
@InbaKrish Please remove the trailing white space here. I'll be working on [adding Rubocop](https://github.com/GymmyComm/genki/issues/5) to the project. Once this is done it will report these sort of issues at the time of creating pull requests.

2023-05-07 14:07 UTC, InbaKrish commented on README.md
> +1. Execute the `docker-compsoe up` command inside the project directory to run the rails server along with the database.
@radar07 Fixed in [fee54fb](https://github.com/GymmyComm/genki/pull/3/commits/fee54fb220793e10a5a10505b4f9c2e06ff8a4a3)

2023-05-07 14:07 UTC, InbaKrish commented on Dockerfile
> +RUN apt-get update && apt-get install -y curl yarn nodejs postgresql-client
Fixed in [fee54fb](https://github.com/GymmyComm/genki/pull/3/commits/fee54fb220793e10a5a10505b4f9c2e06ff8a4a3)

2023-05-08 05:57 UTC, radar07 approved these changes
:+1:

2023-05-08 05:58 UTC, merged